### ISSUE TITLE
Code 

### ISSUE THREAD

**Issue by xgbear** [yiskw713/VideoCaptioning#1]
Hello!Would like to ask if you have the code corresponding to the article link?Thank you very much ~ looking forward to your reply

**Comment by yiskw713** [comment]
Hi, xgbear.

Thank you for visiting my repo.
Do you mean the article link corresponding to my code?
Actually there aren't any articles or papers corresponding to this repository.
I just extended [this image captioning code](https://github.com/yunjey/pytorch-tutorial/tree/master/tutorials/03-advanced/image_captioning) to the video captioning.
I changed an input from an image to a video and replaced 2DCNN with 3DCNN.

If you have any further questions, please do not hesitate to ask me.

Best regards,
yiskw713
